name: go
on: [push,pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.version.outputs.go_version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Cache go module
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-cache-
      - name: Get dependencies, run test
        run: |
          databases=sqlite CGO_ENABLED=1 go test ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      -
        name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6.0.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          git-branch: main
          version-file: version.yml
          git-user-name: Chris Moran
          git-user-email: chris@chrismoran.com
          output-file: CHANGELOG.md

      -
        name: Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
